# Generated by Django 5.0.6 on 2026-03-14 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rental_type', models.CharField(choices=[('room', 'Single Room'), ('self_contain', 'Self Contain'), ('flat', 'Flat / Apartment'), ('hostel', 'Hostel Space'), ('roommate', 'Roommate Needed')], default='room', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_period', models.CharField(choices=[('monthly', 'Per Month'), ('semester', 'Per Semester'), ('annually', 'Per Year'), ('negotiable', 'Negotiable')], default='annually', max_length=20)),
                ('address', models.CharField(help_text='e.g. No. 5 Odim Road, Nsukka', max_length=255)),
                ('area', models.CharField(blank=True, help_text='e.g. Odim, Hilltop, University Road', max_length=100)),
                ('gender_preference', models.CharField(choices=[('any', 'Any Gender'), ('male', 'Male Only'), ('female', 'Female Only')], default='any', max_length=10)),
                ('available_from', models.DateField(blank=True, help_text='Leave blank if available immediately', null=True)),
                ('rooms_available', models.PositiveSmallIntegerField(default=1, help_text='Number of rooms/spaces available')),
                ('amenities', models.CharField(blank=True, help_text='Select all amenities available', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Listing',
                'verbose_name_plural': 'Rental Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rentals/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.rentallisting')),
            ],
        ),
        migrations.CreateModel(
            name='RentalInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_inquiries', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='rentals.rentallisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('rental', 'inquirer')},
            },
        ),
    ]
