# Generated by Django 5.0.6 on 2026-03-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentallisting',
            name='listing_type',
            field=models.CharField(choices=[('offering', 'Room / Space Available'), ('seeking', 'Roommate Wanted')], default='offering', help_text='Are you offering a room or looking for a roommate?', max_length=10),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='video',
            field=models.FileField(blank=True, help_text='Optional walkthrough video. MP4, MOV or WebM. Max 50MB.', null=True, upload_to='rentals/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='rentallisting',
            name='amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rentallisting',
            name='area',
            field=models.CharField(blank=True, help_text='e.g. Odim, Hilltop', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentallisting',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentallisting',
            name='rooms_available',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
