# Generated by Django 5.0.6 on 2026-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentallisting_listing_type_rentallisting_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentallisting',
            name='subsequent_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional payment amount e.g. agency fee or second payment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='subsequent_payment_note',
            field=models.CharField(blank=True, help_text="e.g. 'agency fee', 'agreement fee', 'then ₦120k subsequently'", max_length=120),
        ),
    ]
