# Generated by Django 5.2.14 on 2026-05-31 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rentallisting_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentallisting',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='approved', max_length=16),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='risk_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='rentallisting',
            index=models.Index(fields=['is_active', 'is_taken', '-created_at'], name='rentals_ren_is_acti_b74420_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallisting',
            index=models.Index(fields=['approval_status', 'risk_score', '-created_at'], name='rentals_ren_approva_202577_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallisting',
            index=models.Index(fields=['deleted_at'], name='rentals_ren_deleted_1a82f0_idx'),
        ),
    ]
