# Generated by Django 5.2.14 on 2026-05-30 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trust', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_score', models.PositiveSmallIntegerField()),
                ('new_score', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=80)),
                ('source_object_id', models.CharField(blank=True, max_length=64)),
                ('inputs', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TrustTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='is_actionable',
            field=models.BooleanField(default=False, help_text='Only moderator-confirmed actionable reports affect trust scores.'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'reviewing'])), fields=('reporter', 'content_type', 'object_id'), name='unique_open_report_per_reporter_target'),
        ),
        migrations.AddField(
            model_name='trustscoreevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_trust_score_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trustscoreevent',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='trustscoreevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_trust_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trustscoreevent',
            index=models.Index(fields=['user', '-created_at'], name='trust_trust_user_id_562994_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscoreevent',
            index=models.Index(fields=['reason', '-created_at'], name='trust_trust_reason_aceb94_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscoreevent',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='trust_trust_source__cf27c8_idx'),
        ),
        migrations.AddIndex(
            model_name='trusttransaction',
            index=models.Index(fields=['seller', 'status', '-completed_at'], name='trust_trust_seller__71a0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='trusttransaction',
            index=models.Index(fields=['buyer', 'seller', 'status'], name='trust_trust_buyer_i_353d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='trusttransaction',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='trust_trust_content_68fa53_idx'),
        ),
        migrations.AddConstraint(
            model_name='trusttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('buyer', models.F('seller')), _negated=True), name='trust_transaction_not_self'),
        ),
    ]
