# Generated by Django 5.2.14 on 2026-05-30 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trust', '0002_trustscoreevent_trusttransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trusttransaction',
            name='buyer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='disputed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputed_trust_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='seller_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='trusttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('buyer', 'seller', 'content_type', 'object_id'), name='unique_pending_trust_transaction'),
        ),
    ]
