# Generated by Django 5.2.14 on 2026-05-31 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0003_trusttransaction_buyer_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='code_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_type', models.CharField(choices=[('student_id', 'Student ID'), ('government_id', 'Government ID'), ('business', 'Business verification')], max_length=32)),
                ('document', models.ImageField(blank=True, null=True, upload_to='identity-verification/%Y/%m/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='identity-selfies/%Y/%m/')),
                ('document_reference', models.CharField(blank=True, max_length=128)),
                ('provider', models.CharField(blank=True, help_text='External KYC provider or manual review.', max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('liveness_passed', models.BooleanField(default=False)),
                ('phone_otp_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('risk_score', models.PositiveSmallIntegerField(default=50)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('consent_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_identity_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'risk_score', '-created_at'], name='trust_ident_status_163069_idx'), models.Index(fields=['user', 'verification_type', '-created_at'], name='trust_ident_user_id_34687d_idx'), models.Index(fields=['retention_until'], name='trust_ident_retenti_2291e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSessionSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('new_device', 'New device'), ('new_ip', 'New IP'), ('concurrent_limit', 'Concurrent session limit')], max_length=32)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type', '-created_at'], name='trust_users_user_id_e63bc1_idx'), models.Index(fields=['ip_address', '-created_at'], name='trust_users_ip_addr_43c7da_idx')],
            },
        ),
    ]
