# Generated by Django 5.2.14 on 2026-06-02 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0004_emailotp_code_hash_alter_emailotp_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSellerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(blank=True, max_length=160)),
                ("phone_number", models.CharField(max_length=32)),
                ("public_profile_url", models.URLField(blank=True)),
                (
                    "campus_reason",
                    models.TextField(
                        help_text="Why should this seller be allowed to sell to the campus community?"
                    ),
                ),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="external-seller-proof/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_external_seller_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_seller_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="trust_exter_status_d41aba_idx",
                    ),
                    models.Index(
                        fields=["reviewed_at"], name="trust_exter_reviewe_28c305_idx"
                    ),
                ],
            },
        ),
    ]
