# Generated by Django 5.2.14 on 2026-05-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_response_rate_profile_student_id_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_seller_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_tier',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified_student', 'Verified student'), ('verified_staff', 'Verified staff'), ('verified_external', 'Verified external'), ('verified_business', 'Verified business')], default='unverified', max_length=32),
        ),
    ]
