# Generated by Django 5.2.14 on 2026-06-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_external_seller_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, help_text='Optional UNN matric number (e.g. 2019/234567). Used for manual student verification.', max_length=20),
        ),
    ]
