# Generated by Django 5.2.14 on 2026-05-28 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_production_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='moderation_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='moderation_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged for review'), ('blocked', 'Blocked')], default='clean', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='original_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['moderation_status', '-created_at'], name='messaging_m_moderat_eef485_idx'),
        ),
    ]
