# Generated by Django 5.0.6 on 2026-05-23 10:26

from django.db import migrations, models


def copy_parent_icons(apps, schema_editor):
    ServiceSubCategory = apps.get_model('services', 'ServiceSubCategory')
    for subcategory in ServiceSubCategory.objects.select_related('category'):
        subcategory.icon = subcategory.category.icon if subcategory.category_id else ''
        subcategory.save(update_fields=['icon'])


def clear_icons(apps, schema_editor):
    ServiceSubCategory = apps.get_model('services', 'ServiceSubCategory')
    ServiceSubCategory.objects.update(icon='')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subcategory_and_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon e.g. palette', max_length=10),
        ),
        migrations.RunPython(copy_parent_icons, clear_icons),
    ]
