# Generated by Django 5.0.6 on 2026-05-23 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_subcategory_icons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon e.g. 🎨', max_length=10),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['is_active', '-created_at'], name='services_se_is_acti_8fc990_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['category', 'subcategory', '-created_at'], name='services_se_categor_48df92_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['delivery_mode', '-created_at'], name='services_se_deliver_62ff71_idx'),
        ),
    ]
