# Generated by Django 5.2.14 on 2026-05-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_production_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Service Sub Categories'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='service-categories/banners/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='service-subcategories/banners/'),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon', max_length=10),
        ),
    ]
