# Generated by Django 5.2.14 on 2026-05-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
