# Generated by Django 5.0.6 on 2026-03-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, help_text='Optional. MP4, MOV or WebM. Max 50MB.', null=True, upload_to='listings/videos/%Y/%m/'),
        ),
    ]
