# Generated by Django 5.0.6 on 2026-05-21 20:26

import apps.marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_category_icons_and_subcats'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(default=apps.marketplace.models.default_listing_expiry),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('used', 'Used')], default='used', max_length=20),
        ),
    ]
