# Generated by Django 5.0.6 on 2026-05-23 10:26

from django.db import migrations, models


def copy_parent_icons(apps, schema_editor):
    SubCategory = apps.get_model('marketplace', 'SubCategory')
    for subcategory in SubCategory.objects.select_related('category'):
        subcategory.icon = subcategory.category.icon if subcategory.category_id else ''
        subcategory.save(update_fields=['icon'])


def clear_icons(apps, schema_editor):
    SubCategory = apps.get_model('marketplace', 'SubCategory')
    SubCategory.objects.update(icon='')


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_normalize_listing_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon e.g. phone', max_length=10),
        ),
        migrations.RunPython(copy_parent_icons, clear_icons),
    ]
