# Generated by Django 5.0.6 on 2026-05-23 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_subcategory_icons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon e.g. 📱', max_length=10),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active', 'is_sold', 'expires_at', '-created_at'], name='marketplace_is_acti_bd166e_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'subcategory', '-created_at'], name='marketplace_categor_9307fc_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['condition', '-created_at'], name='marketplace_conditi_af3130_idx'),
        ),
    ]
