# Generated by Django 5.2.14 on 2026-05-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_seed_campus_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
